import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./calender.css";
import "react-datepicker/dist/react-datepicker.css";
import NavBar from "@/components/header";
import QueryClientProvider from "./QueryClientProvider";
import { AuthProvider } from "./auth/Provider";
import { Sidebar } from "@/components/sidebar";
const font = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NavBar />
        <QueryClientProvider>
          <AuthProvider>
            <main className="p-2">{children}</main>
          </AuthProvider>
        </QueryClientProvider>
        <Sidebar />
      </body>
    </html>
  );
}
